apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: default
spec:
  selector:
    app: nexus
  ports:
    - name: http
      port: 8081
    - name: docker-http
      port: 5000

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: default
  labels:
    app: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
        version: v1
    spec:
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-data
      containers:
      - name: nexus
        image: sonatype/nexus3:latest
        env:
          - name: INSTALL4J_ADD_VM_PARAMS
            value: -Xmx500m -Xms300m -XX:MaxDirectMemorySize=800m
        ports:
        - containerPort: 8081
        - containerPort: 5000
        volumeMounts:
          - mountPath: /nexus-data
            name: nexus-data
