#!/usr/bin/env bash

# todo: curses-like namespace selector

cd $(dirname $(readlink -f $0))

source /usr/local/etc/colors.sh
source .scripts/kube.sh

namespace="${1}"
secretName="${2}"

if [[ n"${namespace}" == "n" ]] || [[ n"${secretName}" == "n" ]]; then
    echo "usage: ${highlight}create-secret${clr} ${cyan}<${clr}${highlight}namespace${clr}${cyan}>${clr} ${cyan}<${clr}${highligh}secretName${clr}${cyan}>${clr}"
    exit 1
fi

if ! $kube get namespace "${namespace}" &>/dev/null; then
    echo "${error}Namespace ${cyan}${namespace}${cyan} doesn't exist!" >&2
    exit 1
fi

q="${highligh}>>> ${clr}"
gray="${esc}[90m"

if [[ n"${usernameKey}" == "n" ]]; then
  echo -n "${q}Enter username key name ${cyan}[${clr}${gray}username${clr}${cyan}]${clr}: "
  read usernameKey
  usernameKey=${usernameKey:-username}
fi

if [[ n"${passwordKey}" == "n" ]]; then
  echo -n "${q}Enter password key name ${cyan}[${clr}${gray}passphrase${clr}${cyan}]${clr}: "
  read passwordKey
  passwordKey=${passwordKey:-passphrase}
fi

echo -n "${q}Enter username ${cyan}(${clr}${highlight}${usernameKey}${clr}${cyan})${clr}: "
read username

echo -n "${q}Enter password ${cyan}(${clr}${highlight}${passwordKey}${clr}${cyan})${clr}: "
read -s password

{
    echo 'apiVersion: v1'
    echo 'kind: Secret'
    echo 'metadata:'
    echo "  name: ${secretName}"
    echo "  namespace: ${namespace}"
    echo "type: Opaque"
    echo "data:"
    echo "  ${usernameKey}: $(echo -n "${username}" | base64)"
    echo "  ${passwordKey}: $(echo -n "${password}" | base64)"
} | $kube apply -f - &> /dev/null || {
  echo "${error}Failed to create secret"
  exit 1
}
echo