- name: "[kube-secret {{ transfer_secret.name }}] check if already transferred"
  shell: "{{ kube }} get secret --namespace={{ transfer_secret.to }} {{ transfer_secret.name }} &> /dev/null || echo -n nope"
  register: already_transferred

- name: "[kube-secret {{ transfer_secret.name }}] get secret"
  shell: "{{ kube }} get secret -oyaml {{ transfer_secret.name }} --namespace={{ transfer_secret.from }}"
  register: secret_kube_yaml_raw
  when: already_transferred.stdout == "nope"

- name: "[kube-secret {{ transfer_secret.name }}] load secret"
  set_fact:
    secret_kube_yaml: "{{ secret_kube_yaml_raw.stdout | from_yaml }}"
  when: already_transferred.stdout == "nope"

- name: "[kube-secret {{ transfer_secret.name }}] prepare secret"
  set_fact:
    new_secret:
      apiVersion: v1
      kind: Secret
      data: "{{ secret_kube_yaml.data }}"
      type: Opaque
      metadata:
        name: "{{ transfer_secret.name }}"
        namespace: "{{ transfer_secret.to }}"
  when: already_transferred.stdout == "nope"

- name: "[kube-secret {{ transfer_secret.name }}] load secret"
  shell: "echo {{ new_secret | to_yaml | quote }} | {{ kube }} apply --namespace={{ transfer_secret.to }} -f -"
  when: already_transferred.stdout == "nope"
