apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: blog-gw
  namespace: blog
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http2
        protocol: HTTP
      hosts:
        - saksmt.dev
        - smt.run
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: blog
  namespace: blog
spec:
  hosts:
    - saksmt.dev
    - smt.run
  gateways:
    - blog-gw
  http:
    - route:
        - destination:
            host: blog-frontend.blog.svc.cluster.local
            port:
              number: 80
      match:
        - uri:
            prefix: /
